export const cartaDefecto: Record<string, any[]> = {
  raciones: [
    { nombre: 'Jamón Ibérico', precio: '27,50€' },
    { nombre: 'Jamón Ibérico (con Pan tostado y Tomate)', precio: '28,50€' },
    { nombre: 'Lomo Ibérico', precio: '29,50€' },
    { nombre: 'Queso Flor de Esgueva', precio: '20,00€' },
    { nombre: 'Mixta de Jamón y Queso', precio: '26,00€' },
    { nombre: 'Morcilla de Burgos', precio: '10,50€' },
    { nombre: 'Ensaladilla Rusa', precio: '10,00€' },
    { nombre: 'Croquetas Caseras', precio: '12,00€' },
    { nombre: 'Boquerones', precio: '12,50€' },
    { nombre: 'Sepia a la Plancha', precio: '15,00€' },
    { nombre: 'Gambas a la Plancha (16 uds.)', precio: '26,50€' },
    { nombre: 'Gambón a la Plancha (10 uds.)', precio: '20,00€' },
    { nombre: 'Tabla de Ibéricos', precio: '33,00€' },
    { nombre: 'Chopitos', precio: '13,50€' },
    { nombre: 'Lacón a la Gallega', precio: '12,00€' },
    { nombre: 'Pulpo', precio: '26,00€' },
    { nombre: 'Berenjena estilo La Flecha con Miel', precio: '11,00€' },
    { nombre: 'Calamares', precio: '14,50€' },
    { nombre: 'Alitas', precio: '11,00€' },
    { nombre: 'Oreja a la Plancha', precio: '12,00€' },
    { nombre: 'Patatas Flecha', precio: '9,00€' },
    { nombre: 'Cazuela de Gulas y Gambas', precio: '13,00€' },
    { nombre: 'Pimientos del Padrón', precio: '11,00€' },
    { nombre: 'Torrezno de Soria', precio: '12,00€' },
  ],
  entradas: [
    { nombre: 'Ensalada César', precio: '12,50€' },
    { nombre: 'Ensalada Mixta', precio: '12,50€' },
    { nombre: 'Ensalada de Burrata', precio: '13,00€' },
    { nombre: 'Alcachofas Confitadas con Papada Ibérica y Salsa Romescu', precio: '14,00€' },
    { nombre: 'Huevos Rotos con Jamón Ibérico', precio: '22,00€' },
    { nombre: 'Huevos Rotos con Chistorra', precio: '15,00€' },
    { nombre: 'Huevos Rotos con Torreznos de Soria', precio: '18,50€' },
  ],
  carnes: [
    { nombre: 'Paletilla de Cordero Lechal', precio: '35,00€' },
    { nombre: 'Rabo Estofado al Pedro Ximenez', precio: '28,00€' },
    { nombre: 'Solomillo de Ternera con Salsa Roquefort', precio: '27,00€' },
    { nombre: 'Chuletitas de Lechal', precio: '27,00€' },
    { nombre: 'Entrecot', precio: '24,00€' },
    { nombre: 'Chuletón de Vaca Madurado', precio: '70,00€/kg' },
    { nombre: 'Cachopo Asturiano', precio: '22,00€' },
    { nombre: 'Cachopo Pío Pío', precio: '15,00€', descripcion: 'Pollo relleno de Bacon y Doble Queso' },
    { nombre: 'Cachopo Especial Flecha', precio: '23,50€', descripcion: 'Ternera 100% Asturiana rellena de Cecina de Tineo, Rulo de Cabra Puro y Cebolla Caramelizada' },
  ],
  pescados: [
    { nombre: 'Rodaballo a la Plancha con Sofrito de Ajo', precio: '28,00€' },
    { nombre: 'Lubina Fresca a la Espalda o Bilbaína', precio: '20,00€' },
  ],
  especialidades: [
    { nombre: 'Fritura de Pescado', precio: '28,00€', nota: 'Para 2 personas' },
    { nombre: 'Parrillada de Marisco', precio: '75,00€', nota: 'Para 2 personas' },
    { nombre: 'Parrillada de Carnes', precio: '32,00€', nota: 'Para 2 personas · Con Salsa Chimichurri' },
    { nombre: 'Verdura de Temporada a la Plancha', precio: '18,00€', nota: 'Para 2 personas' },
  ],
  bocadillos: [
    { nombre: 'Jamón Ibérico', precio: '12,00€' },
    { nombre: 'Lomo', precio: '7,00€' },
    { nombre: 'Lomo con Queso', precio: '7,50€' },
    { nombre: 'Lomo con Pimientos', precio: '7,50€' },
    { nombre: 'Lomo Ibérico', precio: '12,50€' },
    { nombre: 'Bacon', precio: '6,50€' },
    { nombre: 'Bacon con Pimiento', precio: '7,00€' },
    { nombre: 'Bacon con Queso', precio: '7,00€' },
    { nombre: 'Tortilla de Patata', precio: '6,50€' },
    { nombre: 'Calamares', precio: '7,00€' },
    { nombre: 'Queso Flor de Esgueva', precio: '8,00€' },
    { nombre: 'Pepito de Ternera', precio: '9,00€' },
    { nombre: 'Salmón', precio: '8,00€' },
    { nombre: 'Bonito con Tomate', precio: '7,00€' },
    { nombre: 'Panceta', precio: '6,50€' },
    { nombre: 'Pollo a la Plancha', precio: '8,00€' },
  ],
  torradas: [
    { nombre: 'De Anchoas (2 uds.)', precio: '8,50€' },
    { nombre: 'De Salmón (2 uds.)', precio: '8,50€' },
    { nombre: 'De Bonito (2 uds.)', precio: '8,50€' },
    { nombre: 'De Solomillo con Queso de Cabra y Cebolla Caramelizada', precio: '9,00€' },
    { nombre: 'De Jamón Ibérico (2 uds.)', precio: '11,30€' },
    { nombre: 'De Lomo Ibérico (2 uds.)', precio: '12,00€' },
    { nombre: 'Combinada de 5 Variedades (10 uds.)', precio: '27,00€' },
  ],
  sandwiches: [
    { nombre: 'Sándwich Vegetal', precio: '6,50€', descripcion: 'Tomate, Lechuga, Espárrago, Huevo duro y Mahonesa' },
    { nombre: 'Sándwich Flecha', precio: '7,50€', descripcion: 'Vegetal más Mixto, Bacon y Huevo a la plancha' },
    { nombre: 'Sándwich Flecha con Pollo', precio: '9,00€' },
    { nombre: 'Sándwich de Jamón', precio: '4,50€' },
    { nombre: 'Sándwich Mixto (Jamón y Queso)', precio: '5,00€' },
    { nombre: 'Sándwich Mixto con Huevo', precio: '5,75€' },
  ],
  extras: [
    { nombre: 'Perrito Caliente', precio: '4,00€' },
    { nombre: 'Patatas Fritas', precio: '4,50€' },
  ],
  combinados: [
    { nombre: 'Nº1: Filete de Ternera, Tortilla Francesa, Patatas Fritas y Ensalada', precio: '15,50€' },
    { nombre: 'Nº2: 2 Hamburguesas con 2 Huevos, Patatas Fritas y Ensalada', precio: '14,50€' },
    { nombre: 'Nº3: 3 Cintas de Lomo, 2 Huevos Fritos y Patatas Fritas', precio: '14,50€' },
    { nombre: 'Nº4: Filete de Pollo a la Plancha con Patatas Fritas y Ensalada', precio: '14,50€' },
  ],
  postres: [
    { nombre: 'Natillas', precio: '4,80€' },
    { nombre: 'Pudding', precio: '4,80€' },
    { nombre: 'Flan', precio: '4,80€' },
    { nombre: 'Fruta del Tiempo', precio: '2,50€' },
    { nombre: 'Arroz con Leche', precio: '4,80€' },
    { nombre: 'Tarta de Galleta', precio: '5,00€' },
    { nombre: 'Tarta de Queso', precio: '5,00€' },
  ],
  vinosTintos: [
    { nombre: 'Viña Eguía Crianza (D.O. Rioja)', botella: '18,50€', copa: '3,20€ / 3,50€' },
    { nombre: 'Ramón Bilbao Crianza (D.O. Rioja)', botella: '19,50€', copa: '3,30€ / 3,60€' },
    { nombre: 'Luis Cañas Crianza (D.O. Rioja)', botella: '22,00€', copa: '3,70€ / 4,00€' },
    { nombre: 'Protos Roble (D.O. Rivera)', botella: '19,00€', copa: '3,30€ / 3,60€' },
    { nombre: 'Protos Crianza (D.O. Rivera)', botella: '29,00€' },
    { nombre: 'Emilio Moro Crianza (D.O. Rivera)', botella: '29,00€' },
    { nombre: 'Matarromera Crianza (D.O. Rivera)', botella: '38,00€' },
    { nombre: 'Amaren (D.O. Rioja)', botella: '29,00€', copa: '4,80€ / 5,10€' },
    { nombre: 'Amaren Ángeles (D.O. Rioja)', botella: '39,00€' },
  ],
  vinosBlancos: [
    { nombre: 'Alma Semidulce (D.O. Vinos de Madrid)', botella: '17,00€', copa: '3,20€ / 3,40€' },
    { nombre: 'Diamante Semidulce (D.O. Rueda)', botella: '17,00€' },
    { nombre: 'Monasterio De Palazuelos Verdejo (D.O. Rueda)', botella: '16,00€', copa: '2,70€ / 2,90€' },
    { nombre: 'Protos Verdejo (D.O. Rueda)', botella: '17,50€', copa: '3,30€ / 3,60€' },
    { nombre: 'Pazo Cilleiro Albariño (D.O. Rías Baixas)', botella: '21,00€', copa: '3,70€ / 4,10€' },
    { nombre: 'Gran Feudo (D.O. Navarra)', botella: '18,00€', copa: '3,20€ / 3,40€' },
    { nombre: 'Mar de Frades (D.O. Rías Baixas)', botella: '29,00€' },
  ],
  otrosVinos: [
    { nombre: 'Tinto de Verano', precio: '3,05€ / 3,35€' },
    { nombre: 'Copa de Sangría', precio: '3,30€ / 3,50€' },
    { nombre: 'Jarra Sangría (1 litro)', precio: '13,50€ / 13,00€' },
  ],
};
